<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="SeedData\equity_groups.json" />
    <Content Remove="SeedData\equity_group_members.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="SeedData\equity_groups.json" />
    <None Include="SeedData\equity_group_members.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="fyers-api-v3" Version="1.2.0" />
    <PackageReference Include="fyerscsharpsdk" Version="1.0.0" />
	<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.4" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="10.0.4" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.4" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.4">
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  <PrivateAssets>all</PrivateAssets>
	</PackageReference>
	<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	<PackageReference Include="prometheus-net.AspNetCore" Version="8.2.1" />
	<PackageReference Include="Microsoft.Extensions.Options" Version="11.0.0-preview.4.26230.115" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="11.0.0-preview.4.26230.115" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlgoTrading.Application\AlgoTrading.Application.csproj" />
    <ProjectReference Include="..\AlgoTrading.Contracts\AlgoTrading.Contracts.csproj" />
	<ProjectReference Include="..\AlgoTrading.Infrastructure\AlgoTrading.Infrastructure.csproj" />

  </ItemGroup>

</Project>
