// src/AlgoTrading.Infrastructure/Persistence/Configurations/PaperOrderConfiguration.cs
using AlgoTrading.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AlgoTrading.Infrastructure.Persistence.Configurations;

/// <summary>
/// Entity Framework Core configuration for the <see cref="PaperOrder"/> entity.
/// Defines the schema for paper trading orders generated by the strategy engine.
/// </summary>
public class PaperOrderConfiguration : IEntityTypeConfiguration<PaperOrder>
{
    public void Configure(EntityTypeBuilder<PaperOrder> builder)
    {
        builder.ToTable("paper_orders");

        builder.HasKey(x => x.Id);

        builder.Property(x => x.StrategyName).IsRequired().HasMaxLength(100);
        builder.Property(x => x.GroupId).HasMaxLength(100);
        builder.Property(x => x.Symbol).IsRequired().HasMaxLength(100);
        builder.Property(x => x.Side).IsRequired().HasMaxLength(20);
        builder.Property(x => x.OrderType).IsRequired().HasMaxLength(50);
        builder.Property(x => x.Status).IsRequired().HasMaxLength(50);

        builder.Property(x => x.RequestedPrice).HasColumnType("numeric(18,6)");
        builder.Property(x => x.FillPrice).HasColumnType("numeric(18,6)");

        builder.Property(x => x.CreatedUtc).IsRequired();

        builder.HasIndex(x => x.SimulationRunId);
        builder.HasIndex(x => x.SimulationSignalId);
        builder.HasIndex(x => x.GroupId);
    }
}