<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<NoWarn>$(NoWarn);NU1701</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\AlgoTrading.Application\AlgoTrading.Application.csproj" />
		<ProjectReference Include="..\AlgoTrading.Domain\AlgoTrading.Domain.csproj" />
		<ProjectReference Include="..\AlgoTrading.Contracts\AlgoTrading.Contracts.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="fyers-api-v3" Version="1.2.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.0" />
		<PackageReference Include="StackExchange.Redis" Version="2.8.24" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.4" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.4" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.4">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
		<PackageReference Include="prometheus-net" Version="8.2.1" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.1" />
		<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.0.1" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

</Project>