#!/usr/bin/env bash
# Moves the platform's data from the Mac to the server, in two halves:
#
#   ./scripts/aws/migrate-db.sh dump                  (on the Mac)
#       -> algotrading-<date>.tar in the current directory:
#          the database (everything except raw ticks) and the ASP.NET data
#          protection keys that the stored broker credentials, trading PIN and
#          FYERS tokens are encrypted with. Without the keys the server could
#          not read them and you would re-enter the FYERS app credentials.
#
#   ./scripts/aws/migrate-db.sh restore <file.tar>    (on the server)
#       -> starts the API once so the migrations create the schema, empties
#          the seeded tables, loads the dump, installs the keys.
#
# Raw ticks (live_ticks, market_ticks — seven rolling days, ~6 GB) are NOT
# carried over: they are regenerated by the next session and the console
# reads bars, candles, chains, runs and positions, all of which are included.
# Both halves talk to the database through the algotrading_db container, so
# no PostgreSQL client is needed on either machine.

set -euo pipefail
# REPO_ROOT may be given when the script runs from outside the checkout (the
# first restore happens before the server's checkout carries this file).
cd "${REPO_ROOT:-$(dirname "$0")/../..}"
REPO_ROOT="$PWD"
KEYS_DIR="$HOME/.aspnet/DataProtection-Keys"

db() { docker exec -i algotrading_db "$@"; }
say() { printf '%s  %s\n' "$(date '+%H:%M:%S')" "$1"; }

dump() {
  local stamp; stamp="$(date '+%Y%m%d-%H%M')"
  local work; work="$(mktemp -d)"
  say "dumping the database (public schema, data only, without raw ticks) ..."
  db pg_dump -U postgres -d algotrading --data-only --format=custom --schema=public \
      --exclude-table-data=live_ticks --exclude-table-data=market_ticks \
      --exclude-table='"__EFMigrationsHistory"' > "$work/algotrading.dump"
  say "  $(du -h "$work/algotrading.dump" | cut -f1)"
  if [ -d "$KEYS_DIR" ]; then
    mkdir -p "$work/DataProtection-Keys" && cp "$KEYS_DIR"/*.xml "$work/DataProtection-Keys/" 2>/dev/null || true
    say "  data protection keys: $(ls "$work/DataProtection-Keys" | wc -l | tr -d ' ') file(s)"
  else
    say "  WARNING: no data protection keys at $KEYS_DIR — broker credentials will have to be re-entered on the server"
  fi
  local out="$REPO_ROOT/algotrading-$stamp.tar"
  tar -cf "$out" -C "$work" .
  rm -rf "$work"
  say "wrote $out ($(du -h "$out" | cut -f1)). Copy it to the server: scp -i key.pem $(basename "$out") ubuntu@<ip>:~/"
}

restore() {
  local tarfile="${1:-}"; [ -f "$tarfile" ] || { echo "usage: $0 restore <algotrading-*.tar>" >&2; exit 2; }
  . scripts/lib/desk-common.sh
  local work; work="$(mktemp -d)"; tar -xf "$tarfile" -C "$work"
  [ -f "$work/algotrading.dump" ] || { echo "no algotrading.dump inside $tarfile" >&2; exit 1; }

  say "stopping the desk and the API (if running) ..."
  sudo systemctl stop algotrading-desk 2>/dev/null || true
  api_stop
  say "infra up ..."; ( docker compose up -d --wait timescaledb redis >/dev/null )

  # The schema comes from the migrations, never from the dump: start the API
  # once, let it migrate and seed, then stop it. That is also what proves the
  # build runs on this machine before any data is involved.
  say "starting the API once to create the schema ..."
  api_start || { echo "the API did not start — fix that first (logs/api.log)" >&2; exit 1; }
  api_stop

  say "emptying the seeded tables (the dump carries the real rows) ..."
  local tables
  tables="$(db psql -U postgres -d algotrading -Atc "select string_agg(format('%I', table_name), ', ') from information_schema.tables where table_schema='public' and table_type='BASE TABLE' and table_name not in ('__EFMigrationsHistory','live_ticks','market_ticks')")"
  db psql -U postgres -d algotrading -qc "TRUNCATE $tables RESTART IDENTITY CASCADE"

  say "loading the dump ..."
  db pg_restore -U postgres -d algotrading --data-only --disable-triggers --no-owner < "$work/algotrading.dump" \
    || { echo "pg_restore reported errors above; the ones about live_ticks/market_ticks (no data) are expected" >&2; }
  say "  rows: users $(db psql -U postgres -d algotrading -Atc 'select count(*) from app_user'), runs $(db psql -U postgres -d algotrading -Atc 'select count(*) from simulation_runs'), candles $(db psql -U postgres -d algotrading -Atc 'select count(*) from candles'), chain rows $(db psql -U postgres -d algotrading -Atc 'select count(*) from option_chain_snapshots')"

  if [ -d "$work/DataProtection-Keys" ]; then
    mkdir -p "$KEYS_DIR"; cp "$work/DataProtection-Keys"/*.xml "$KEYS_DIR"/; chmod 600 "$KEYS_DIR"/*.xml
    say "data protection keys installed at $KEYS_DIR"
  fi
  rm -rf "$work"
  say "done. Start the desk:  sudo systemctl start algotrading-desk   then  ./scripts/status.sh"
}

case "${1:-}" in
  dump) dump;;
  restore) restore "${2:-}";;
  *) echo "usage: $0 dump | restore <file.tar>" >&2; exit 2;;
esac
