<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-AlgoTrading.Worker.Strategy-63981c09-34cb-4441-8ab7-552143b23038</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="fyers-api-v3" Version="1.2.0" />
    <PackageReference Include="fyerscsharpsdk" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="11.0.0-preview.4.26230.115" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="11.0.0-preview.4.26230.115" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="11.0.0-preview.4.26230.115" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.2.1" />
  </ItemGroup>
</Project>
