// src/AlgoTrading.Domain/Entities/PaperPosition.cs
namespace AlgoTrading.Domain.Entities;

/// <summary>
/// Represents an open or closed simulated position generated by a paper-trading strategy.
/// Tracks the entry and exit logic, quantities, and real-time profitability (PnL).
/// </summary>
public class PaperPosition
{
    /// <summary>
    /// Primary key.
    /// </summary>
    public long Id { get; set; }

    /// <summary>
    /// The unique identifier of the simulation or paper-trading run this position belongs to.
    /// Used to group performance metrics per backtest or forward test.
    /// </summary>
    public long SimulationRunId { get; set; }

    /// <summary>
    /// The name of the strategy that opened this position (e.g., "ExampleStraddle").
    /// </summary>
    public string StrategyName { get; set; } = string.Empty;

    /// <summary>
    /// An optional identifier to group multiple related positions together (e.g., legs of a Straddle or Butterfly).
    /// </summary>
    public string GroupId { get; set; } = string.Empty;

    /// <summary>
    /// The specific instrument symbol being traded (e.g., "NSE:BANKNIFTY24JUN50000CE").
    /// </summary>
    public string Symbol { get; set; } = string.Empty;

    /// <summary>
    /// The direction of the trade: "LONG" (bought) or "SHORT" (sold).
    /// </summary>
    public string Direction { get; set; } = string.Empty;

    /// <summary>
    /// The number of shares or contracts held in this position.
    /// </summary>
    public int Quantity { get; set; }

    /// <summary>
    /// The average execution price at which the position was entered.
    /// </summary>
    public decimal AveragePrice { get; set; }

    /// <summary>
    /// The most recent market price used to calculate Unrealized PnL.
    /// </summary>
    public decimal? LastMarkPrice { get; set; }

    /// <summary>
    /// The actual profit or loss locked in upon closing portions (or all) of the position.
    /// </summary>
    public decimal RealizedPnl { get; set; }

    /// <summary>
    /// The paper profit or loss if the position were to be closed at the <see cref="LastMarkPrice"/>.
    /// </summary>
    public decimal UnrealizedPnl { get; set; }

    /// <summary>
    /// The lifecycle state of the position: "Open" or "Closed".
    /// </summary>
    public string Status { get; set; } = "Open";

    /// <summary>
    /// When the position was initially opened.
    /// </summary>
    public DateTime OpenedUtc { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// When the position was fully closed (if applicable).
    /// </summary>
    public DateTime? ClosedUtc { get; set; }

    /// <summary>
    /// When this record was last modified in the database.
    /// </summary>
    public DateTime UpdatedUtc { get; set; } = DateTime.UtcNow;
}