// src/AlgoTrading.Domain/Entities/PaperPosition.cs
namespace AlgoTrading.Domain.Entities;

/// <summary>
/// Represents an open or closed simulated position generated by a paper-trading strategy.
/// Tracks the entry and exit logic, quantities, and real-time profitability (PnL).
/// </summary>
public class PaperPosition
{
    /// <summary>
    /// Primary key.
    /// </summary>
    public long Id { get; set; }

    /// <summary>
    /// The unique identifier of the simulation or paper-trading run this position belongs to.
    /// Used to group performance metrics per backtest or forward test.
    /// </summary>
    public long SimulationRunId { get; set; }

    /// <summary>
    /// The name of the strategy that opened this position (e.g., "ExampleStraddle").
    /// </summary>
    public string StrategyName { get; set; } = string.Empty;

    /// <summary>
    /// An optional identifier to group multiple related positions together (e.g., legs of a Straddle or Butterfly).
    /// </summary>
    public string GroupId { get; set; } = string.Empty;

    /// <summary>
    /// The specific instrument symbol being traded (e.g., "NSE:BANKNIFTY24JUN50000CE").
    /// </summary>
    public string Symbol { get; set; } = string.Empty;

    /// <summary>
    /// The direction of the trade: "LONG" (bought) or "SHORT" (sold).
    /// </summary>
    public string Direction { get; set; } = string.Empty;

    /// <summary>
    /// The number of shares or contracts held in this position.
    /// </summary>
    public int Quantity { get; set; }

    /// <summary>
    /// The average execution price at which the position was entered.
    /// </summary>
    public decimal AveragePrice { get; set; }

    /// <summary>
    /// The most recent market price used to calculate Unrealized PnL.
    /// </summary>
    public decimal? LastMarkPrice { get; set; }

    /// <summary>
    /// The actual profit or loss locked in upon closing portions (or all) of the position.
    /// </summary>
    public decimal RealizedPnl { get; set; }

    /// <summary>
    /// The paper profit or loss if the position were to be closed at the <see cref="LastMarkPrice"/>.
    /// </summary>
    public decimal UnrealizedPnl { get; set; }

    /// <summary>
    /// The lifecycle state of the position: "Open" or "Closed".
    /// </summary>
    public string Status { get; set; } = "Open";

    /// <summary>
    /// When the position was initially opened.
    /// </summary>
    public DateTime OpenedUtc { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// When the position was fully closed (if applicable).
    /// </summary>
    public DateTime? ClosedUtc { get; set; }

    /// <summary>
    /// When this record was last modified in the database.
    /// </summary>

    /// <summary>
    /// Price levels that belong to THIS position, set when the order was placed.
    /// </summary>
    /// <remarks>
    /// A run's leg rules are one setting shared by every position in it, which
    /// is fine for a strategy trading one instrument and wrong for a book held
    /// by hand: "stop 9 points" is 1.3% on a share at 703 and 310% on an option
    /// at 2.90. A hand-placed order carries its own stop and target, in PRICE,
    /// because that is what the trader decided at the moment they placed it.
    ///
    /// Null means "no rule of its own" - the run's leg rules still apply.
    /// </remarks>
    public decimal? StopLossPrice { get; set; }

    /// <inheritdoc cref="StopLossPrice"/>
    public decimal? TargetPrice { get; set; }

    public DateTime UpdatedUtc { get; set; } = DateTime.UtcNow;
}