#!/usr/bin/env python3
"""
Generate the git-ignored `appsettings.Local.json` files from the repo-root `.env`.

Shared by scripts/setup.sh and scripts/setup.ps1 so the mapping from .env keys
to .NET configuration keys is defined exactly once, and so JSON/connection-string
escaping is handled correctly on every platform.

Usage:  python3 scripts/_gen_local_settings.py [--quiet]
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
ENV_FILE = REPO_ROOT / ".env"

API_SETTINGS = REPO_ROOT / "src" / "AlgoTrading.Api" / "appsettings.Local.json"
WORKER_SETTINGS = (
    REPO_ROOT / "src" / "AlgoTrading.Worker.MarketData" / "appsettings.Local.json"
)

BANNER = (
    "GENERATED by scripts/setup.sh|ps1 from the repo-root .env. "
    "Do not edit by hand and do not commit — edit .env and re-run setup instead."
)


def read_env(path: Path) -> dict[str, str]:
    """Parse a dotenv file. Ignores comments/blank lines, strips paired quotes."""
    values: dict[str, str] = {}
    if not path.is_file():
        return values

    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
            value = value[1:-1]
        values[key] = value
    return values


def npgsql_value(value: str) -> str:
    """Quote a connection-string value the way Npgsql expects.

    Npgsql splits on ';' and '=', so a password containing either — or leading /
    trailing whitespace — must be wrapped in double quotes with inner quotes
    doubled. Without this, a perfectly valid password silently produces a
    malformed connection string.
    """
    if value == "":
        return value
    needs_quoting = (
        any(ch in value for ch in ';="\'') or value != value.strip()
    )
    if not needs_quoting:
        return value
    return '"' + value.replace('"', '""') + '"'


def build_connection_string(env: dict[str, str]) -> str:
    parts = [
        f"Host={env.get('POSTGRES_HOST', 'localhost')}",
        f"Port={env.get('POSTGRES_PORT', '5432')}",
        f"Database={npgsql_value(env.get('POSTGRES_DB', 'algotrading'))}",
        f"Username={npgsql_value(env.get('POSTGRES_USER', 'postgres'))}",
        f"Password={npgsql_value(env.get('POSTGRES_PASSWORD', ''))}",
    ]
    return ";".join(parts)


def build_redis_connection(env: dict[str, str]) -> str:
    host = env.get("REDIS_HOST", "localhost")
    port = env.get("REDIS_PORT", "6379")
    conn = f"{host}:{port}"
    password = env.get("REDIS_PASSWORD", "")
    if password:
        conn += f",password={password}"
    return conn


def as_int(env: dict[str, str], key: str, default: int) -> int:
    try:
        return int(env[key])
    except (KeyError, ValueError):
        return default


def as_float(env: dict[str, str], key: str, default: float) -> float:
    try:
        return float(env[key])
    except (KeyError, ValueError):
        return default


def split_csv(value: str) -> list[str]:
    """Split a comma-separated setting into a clean list, dropping empties."""
    return [part.strip() for part in value.split(",") if part.strip()]


def main() -> int:
    quiet = "--quiet" in sys.argv

    if not ENV_FILE.is_file():
        print(f"ERROR: {ENV_FILE} not found. Copy .env.example to .env first.",
              file=sys.stderr)
        return 1

    env = read_env(ENV_FILE)
    connection_string = build_connection_string(env)

    api_settings = {
        "//": BANNER,
        "ConnectionStrings": {"TradingDb": connection_string},
        "Jwt": {
            "Issuer": env.get("JWT_ISSUER", "AlgoTrading.Api"),
            "Audience": env.get("JWT_AUDIENCE", "AlgoTrading.App"),
            "SecretKey": env.get("JWT_SECRET_KEY", ""),
            "AccessTokenMinutes": as_int(env, "JWT_ACCESS_TOKEN_MINUTES", 60),
            "RefreshTokenDays": as_int(env, "JWT_REFRESH_TOKEN_DAYS", 7),
        },
        "Fyers": {
            "ClientId": env.get("FYERS_APP_ID", ""),
            "SecretKey": env.get("FYERS_SECRET_KEY", ""),
            "RedirectUri": env.get(
                "FYERS_REDIRECT_URI", "http://127.0.0.1:5025/api/auth/callback"
            ),
            "DataApiBaseUrl": env.get(
                "FYERS_DATA_API_BASE_URL", "https://api-t1.fyers.in"
            ),
        },
        "RiskManagement": {
            "MaxOrdersPerMinute": as_int(env, "RISK_MAX_ORDERS_PER_MINUTE", 50),
            "MaxDailyLoss": as_float(env, "RISK_MAX_DAILY_LOSS", -50000.0),
        },
        "Bootstrap": {
            "AdminUserName": env.get("ADMIN_USERNAME", "admin"),
            "AdminEmail": env.get("ADMIN_EMAIL", "admin@localhost"),
            # Empty means "generate one and print it once" — see AdminBootstrapper.
            "AdminPassword": env.get("ADMIN_PASSWORD", ""),
            # The Python engine signs in as this account to reach the API.
            "ServiceUserName": env.get("ENGINE_SERVICE_USERNAME", "engine-service"),
            "ServicePassword": env.get("ENGINE_SERVICE_PASSWORD", ""),
        },
        "Cors": {
            "AllowedOrigins": split_csv(
                env.get("CORS_ALLOWED_ORIGINS", "http://localhost:5173,http://localhost:3000")
            ),
        },
        "Telegram": {
            "BotToken": env.get("TELEGRAM_BOT_TOKEN", ""),
            "ChatId": env.get("TELEGRAM_CHAT_ID", ""),
        },
    }

    worker_settings = {
        "//": BANNER,
        "ConnectionStrings": {
            "TradingDb": connection_string,
            "DefaultConnection": connection_string,
        },
        "Redis": {
            "ConnectionString": build_redis_connection(env),
            "StreamName": env.get("REDIS_STREAM_NAME", "market:ticks"),
            "ConsumerGroup": "market-data-workers",
            "ConsumerName": "market-worker-1",
            "ReadBatchSize": 200,
            "PollDelayMs": 500,
        },
    }

    for path, payload in ((API_SETTINGS, api_settings),
                          (WORKER_SETTINGS, worker_settings)):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
        if not quiet:
            print(f"  wrote {path.relative_to(REPO_ROOT)}")

    missing = [
        key
        for key in ("POSTGRES_PASSWORD", "FYERS_APP_ID", "FYERS_SECRET_KEY",
                    "JWT_SECRET_KEY")
        if not env.get(key) or env[key].startswith(("YOUR_", "REPLACE_", "change-me"))
    ]
    if missing and not quiet:
        print(
            "\n  NOTE: these .env values are still placeholders -> "
            + ", ".join(missing)
        )
        print("        Infrastructure will start, but broker login will fail "
              "until they are set.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
