// src/AlgoTrading.Contracts/Simulator/CreateSimulationSignalRequest.cs
namespace AlgoTrading.Contracts.Simulator;

/// <summary>
/// Data Transfer Object representing a raw signal generated by a Python strategy.
/// Submitted to the C# backend to be converted into paper orders.
/// </summary>
public class CreateSimulationSignalRequest
{
    /// <summary>
    /// Parent run ID.
    /// </summary>
    public long SimulationRunId { get; set; }

    /// <summary>
    /// Name of the generating strategy.
    /// </summary>
    public string StrategyName { get; set; } = string.Empty;

    /// <summary>
    /// Type of signal (e.g., ENTRY).
    /// </summary>
    public string SignalType { get; set; } = string.Empty;

    /// <summary>
    /// Timestamp of the market event.
    /// </summary>
    public DateTime TimestampUtc { get; set; }

    /// <summary>
    /// The specific contract symbol.
    /// </summary>
    public string Symbol { get; set; } = string.Empty;

    /// <summary>
    /// Spot or contract price at time of signal.
    /// </summary>
    public decimal? Price { get; set; }

    /// <summary>
    /// Group identifier for multi-leg strategies.
    /// </summary>
    public string GroupId { get; set; } = string.Empty;

    /// <summary>
    /// Debug metadata.
    /// </summary>
    public string MetadataJson { get; set; } = "{}";

    /// <summary>
    /// The legs (individual trades) that make up this signal.
    /// </summary>
    public List<SimulationSignalLegRequest>? Legs { get; set; }
}

/// <summary>
/// Represents a single leg of a multi-leg signal (e.g. one option contract to buy/sell).
/// </summary>
public class SimulationSignalLegRequest
{
    public string Symbol { get; set; } = string.Empty;
    public string Side { get; set; } = string.Empty;
    public int Quantity { get; set; }
    public decimal? Price { get; set; }
}