from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class DataRequirement:
    """
    Defines a data dependency for a strategy.
    symbol_type can be 'index', 'atm_ce', 'atm_pe', or an exact symbol string.
    resolution can be '1m', '5m', '15m', '1D', etc.
    """
    symbol_type: str
    resolution: str

@dataclass
class OptionContract:
    """
    Represents a tradable option contract retrieved from the platform.
    Used by the strategy to identify the exact symbol, strike, and type (CE/PE) to trade.
    """
    symbol: str
    underlying: str
    expiry_date: str
    strike_price: float
    option_type: str
    instrument_type: str = ""
    description: str = ""


@dataclass
class BarFrame:
    """
    Represents a single candlestick (OHLCV) for a given instrument and resolution.
    Used by strategies that rely on historical or recent price action instead of just tick data.
    """
    symbol: str
    resolution: str
    timestamp_utc: str
    open: float
    high: float
    low: float
    close: float
    volume: float = 0.0


@dataclass
class StrategyInput:
    """
    The main data payload delivered to a strategy on every evaluation cycle (e.g., on every new bar or tick).
    Contains the current market context, including the underlying price, selected contracts, and historical bars.
    """
    mode: str  # E.g., 'LivePaper', 'OfflineReplay'
    timestamp_utc: str

    underlying: str  # E.g., 'BANKNIFTY'
    spot_price: float

    # Optional — the strategy can compute the ATM strike itself, or the platform can provide it.
    atm_strike: Optional[int] = None

    # Contextual contracts (e.g., the current ATM CE and PE) provided by the runner.
    contracts: Dict[str, OptionContract] = field(default_factory=dict)

    # Hierarchical bars: e.g. bars["1m"]["index"] or bars["5m"]["atm_ce"]
    bars: Dict[str, Dict[str, List[BarFrame]]] = field(default_factory=dict)

    # Any extra context the runner wants to pass to the strategy.
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class StrategySignal:
    """
    Represents an actionable signal generated by the strategy (e.g., an entry, exit, or adjustment).
    These signals are consumed by the runner or platform to place actual paper/live orders.
    """
    strategy_name: str
    signal_type: str  # E.g., 'ENTRY', 'EXIT', 'ATM_SHIFT'
    timestamp_utc: str
    reason: str  # Human-readable explanation of why the signal fired.

    symbol: Optional[str] = None
    price: Optional[float] = None
    
    # For multi-leg strategies (like Straddles), defines the individual option legs to trade.
    legs: List[Dict[str, Any]] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)


class BaseStrategy:
    """
    The abstract base class for all trading strategies.
    Enforces a pure, stateless design where the strategy logic is evaluated based on an explicit state dictionary.
    """
    name = "BaseStrategy"

    def initialize_state(self) -> Dict[str, Any]:
        """
        Returns a fresh, empty state object.
        The runner calls this once when the strategy starts. The state is then passed back into `on_bar` on every cycle.
        """
        return {}

    @classmethod
    def get_data_requirements(cls) -> List[DataRequirement]:
        """
        Strategies override this to declare the timeframes and symbols they need.
        By default, returns an empty list (meaning it only needs raw ticks).
        """
        return []

    def on_bar(self, state: Dict[str, Any], inp: StrategyInput) -> List[StrategySignal]:
        """
        The core evaluation logic of the strategy.
        Called by the runner every time a new data point (bar/tick) arrives.
        
        :param state: A dictionary holding the strategy's persistent memory across cycles (e.g., current positions).
        :param inp: The current market data and context (prices, bars, contracts).
        :return: A list of actionable StrategySignals.
        """
        raise NotImplementedError("Strategy must implement on_bar().")
