"""
strategies/base_strategy.py

Data contracts shared by every strategy (inputs, signals, contracts, bars) and
the BaseStrategy class they all derive from.

Besides the evaluation hooks (`initialize_state`, `on_bar`) a strategy carries
catalog metadata as plain class attributes: description, category, supported
underlyings, legs summary, default lots and default parameters. The metadata is
read offline by `tools/list_strategies.py` and surfaced by the API as the
strategy library, so keep it accurate and in plain English.

Leg quantities are LOTS everywhere: the platform multiplies by the instrument's
lot size when it fills a paper order.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


# Underlyings a strategy is assumed to handle unless it says otherwise. These
# are the index option families with weekly/monthly contracts in the FYERS
# master; stock options are opt-in per strategy.
DEFAULT_SUPPORTED_UNDERLYINGS: List[str] = ["NIFTY", "BANKNIFTY", "FINNIFTY", "MIDCPNIFTY", "SENSEX"]


@dataclass
class DataRequirement:
    """
    Defines a data dependency for a strategy.
    symbol_type can be 'index', 'atm_ce', 'atm_pe', or an exact symbol string.
    resolution can be '1m', '5m', '15m', '1D', etc.
    """
    symbol_type: str
    resolution: str

@dataclass
class OptionContract:
    """
    Represents a tradable option contract retrieved from the platform.
    Used by the strategy to identify the exact symbol, strike, and type (CE/PE) to trade.
    """
    symbol: str
    underlying: str
    expiry_date: str
    strike_price: float
    option_type: str
    instrument_type: str = ""
    description: str = ""


@dataclass
class BarFrame:
    """
    Represents a single candlestick (OHLCV) for a given instrument and resolution.
    Used by strategies that rely on historical or recent price action instead of just tick data.
    """
    symbol: str
    resolution: str
    timestamp_utc: str
    open: float
    high: float
    low: float
    close: float
    volume: float = 0.0


@dataclass
class StrategyInput:
    """
    The main data payload delivered to a strategy on every evaluation cycle (e.g., on every new bar or tick).
    Contains the current market context, including the underlying price, selected contracts, and historical bars.
    """
    mode: str  # E.g., 'LivePaper', 'OfflineReplay'
    timestamp_utc: str

    underlying: str  # E.g., 'BANKNIFTY'
    spot_price: float

    # Optional — the strategy can compute the ATM strike itself, or the platform can provide it.
    atm_strike: Optional[int] = None

    # Contextual contracts (e.g., the current ATM CE and PE) provided by the runner.
    contracts: Dict[str, OptionContract] = field(default_factory=dict)

    # Hierarchical bars: e.g. bars["1m"]["index"] or bars["5m"]["atm_ce"]
    bars: Dict[str, Dict[str, List[BarFrame]]] = field(default_factory=dict)

    # Any extra context the runner wants to pass to the strategy.
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class StrategySignal:
    """
    Represents an actionable signal generated by the strategy (e.g., an entry, exit, or adjustment).
    These signals are consumed by the runner or platform to place actual paper/live orders.
    """
    strategy_name: str
    signal_type: str  # E.g., 'ENTRY', 'EXIT', 'ATM_SHIFT'
    timestamp_utc: str
    reason: str  # Human-readable explanation of why the signal fired.

    symbol: Optional[str] = None
    price: Optional[float] = None
    
    # For multi-leg strategies (like Straddles), defines the individual option legs to trade.
    legs: List[Dict[str, Any]] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)


class BaseStrategy:
    """
    The abstract base class for all trading strategies.
    Enforces a pure, stateless design where the strategy logic is evaluated based on an explicit state dictionary.
    """
    name = "BaseStrategy"

    # --- Catalog metadata (all optional; override per strategy) ---------------
    # Plain-English summary: what the strategy does, when it profits, what it
    # needs. Falls back to the class docstring when left empty.
    description: str = ""
    # Neutral / Bullish / Bearish / Directional / Adjustment / Example / ...
    category: str = "Other"
    # Underlyings the strategy is designed for (see DEFAULT_SUPPORTED_UNDERLYINGS).
    supported_underlyings: List[str] = list(DEFAULT_SUPPORTED_UNDERLYINGS)
    # The kind of instrument the legs trade. Only "options" is supported today.
    instrument_kind: str = "options"
    # One-line description of the legs, e.g. "Sell ATM CE + Sell ATM PE".
    legs_summary: str = ""
    # Lots per leg when the run does not specify any.
    default_lots: int = 1
    # Tunable parameters and their defaults, merged with the run's parametersJson.
    default_params: Dict[str, Any] = {}
    # Set to False to keep a runnable-but-internal class out of the catalog.
    listed: bool = True

    @staticmethod
    def lots_from(params: Optional[Dict[str, Any]], default: int = 1) -> int:
        """
        Resolve the lots per leg from run parameters.

        Accepts `lots` (the current key) or the legacy `quantity`, falls back to
        `default`, and never returns less than 1.
        """
        source = params or {}
        raw = source.get("lots")
        if raw is None:
            raw = source.get("quantity")
        if raw is None:
            raw = default
        try:
            lots = int(float(raw))
        except (TypeError, ValueError):
            try:
                lots = int(default)
            except (TypeError, ValueError):
                lots = 1
        return max(1, lots)

    def initialize_state(self) -> Dict[str, Any]:
        """
        Returns a fresh, empty state object.
        The runner calls this once when the strategy starts. The state is then passed back into `on_bar` on every cycle.
        """
        return {}

    @classmethod
    def get_data_requirements(cls) -> List[DataRequirement]:
        """
        Strategies override this to declare the timeframes and symbols they need.
        By default, returns an empty list (meaning it only needs raw ticks).
        """
        return []

    def on_bar(self, state: Dict[str, Any], inp: StrategyInput) -> List[StrategySignal]:
        """
        The core evaluation logic of the strategy.
        Called by the runner every time a new data point (bar/tick) arrives.
        
        :param state: A dictionary holding the strategy's persistent memory across cycles (e.g., current positions).
        :param inp: The current market data and context (prices, bars, contracts).
        :return: A list of actionable StrategySignals.
        """
        raise NotImplementedError("Strategy must implement on_bar().")
